#!/bin/bash

# Generate verification data from Terraform outputs
# This script exports Terraform outputs to a bash-sourceable file that
# verification scripts can use instead of querying AWS CLI

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="${SCRIPT_DIR}/terraform_verification_data.sh"

echo "Generating verification data from Terraform outputs..."
echo "Terraform directory: $TERRAFORM_DIR"
echo "Output file: $OUTPUT_FILE"

# Check if we're in a Terraform directory
if [ ! -f "${TERRAFORM_DIR}/outputs.tf" ]; then
    echo "ERROR: Not in a Terraform directory (outputs.tf not found)"
    echo "Expected location: ${TERRAFORM_DIR}/outputs.tf"
    exit 1
fi

# Check if Terraform state exists
if [ ! -f "${TERRAFORM_DIR}/terraform.tfstate" ]; then
    echo "ERROR: Terraform state file not found"
    echo "Please run 'terraform apply' first"
    exit 1
fi

# Export Terraform output to JSON
cd "$TERRAFORM_DIR"
echo "Running: terraform output -json verification_data"
TF_OUTPUT=$(terraform output -json verification_data 2>&1)

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to get Terraform output"
    echo "$TF_OUTPUT"
    exit 1
fi

# Generate bash-sourceable file
cat > "$OUTPUT_FILE" << 'EOF'
#!/bin/bash
# Auto-generated file - DO NOT EDIT MANUALLY
# Generated by: generate_verification_data.sh
# This file contains resource IDs from Terraform outputs

# Set flag to indicate Terraform data is available
TF_DATA_AVAILABLE=true

EOF

# Parse JSON and create bash variables using jq
echo "$TF_OUTPUT" | jq -r '
# Management VPC
"TF_MGMT_VPC_ID=\"\(.management_vpc.vpc_id // "")\"",
"TF_MGMT_IGW_ID=\"\(.management_vpc.igw_id // "")\"",
"TF_JUMP_BOX_PRIVATE_IP=\"\(.management_vpc.jump_box_private_ip // "")\"",
"TF_JUMP_BOX_PUBLIC_IP=\"\(if (.management_vpc.jump_box_public_ip | type) == "array" then .management_vpc.jump_box_public_ip[0] else .management_vpc.jump_box_public_ip // "" end)\"",
"TF_FMGR_PRIVATE_IP=\"\(.management_vpc.fmgr_private_ip // "")\"",
"TF_FMGR_PUBLIC_IP=\"\(if (.management_vpc.fmgr_public_ip | type) == "array" then .management_vpc.fmgr_public_ip[0] else .management_vpc.fmgr_public_ip // "" end)\"",
"TF_FAZ_PRIVATE_IP=\"\(.management_vpc.faz_private_ip // "")\"",
"TF_FAZ_PUBLIC_IP=\"\(if (.management_vpc.faz_public_ip | type) == "array" then .management_vpc.faz_public_ip[0] else .management_vpc.faz_public_ip // "" end)\"",

# Inspection VPC
"TF_INSPECTION_VPC_ID=\"\(.inspection_vpc.vpc_id // "")\"",
"TF_INSPECTION_IGW_ID=\"\(.inspection_vpc.igw_id // "")\"",
"TF_INSPECTION_SUBNET_PUBLIC_AZ1_ID=\"\(.inspection_vpc.subnet_public_az1_id // "")\"",
"TF_INSPECTION_SUBNET_PUBLIC_AZ2_ID=\"\(.inspection_vpc.subnet_public_az2_id // "")\"",
"TF_INSPECTION_SUBNET_PRIVATE_AZ1_ID=\"\(.inspection_vpc.subnet_private_az1_id // "")\"",
"TF_INSPECTION_SUBNET_PRIVATE_AZ2_ID=\"\(.inspection_vpc.subnet_private_az2_id // "")\"",
"TF_INSPECTION_SUBNET_GWLBE_AZ1_ID=\"\(.inspection_vpc.subnet_gwlbe_az1_id // "")\"",
"TF_INSPECTION_SUBNET_GWLBE_AZ2_ID=\"\(.inspection_vpc.subnet_gwlbe_az2_id // "")\"",
"TF_INSPECTION_SUBNET_NATGW_AZ1_ID=\"\(.inspection_vpc.subnet_natgw_az1_id // "")\"",
"TF_INSPECTION_SUBNET_NATGW_AZ2_ID=\"\(.inspection_vpc.subnet_natgw_az2_id // "")\"",
"TF_INSPECTION_RT_PUBLIC_AZ1_ID=\"\(.inspection_vpc.route_table_public_az1_id // "")\"",
"TF_INSPECTION_RT_PUBLIC_AZ2_ID=\"\(.inspection_vpc.route_table_public_az2_id // "")\"",
"TF_INSPECTION_RT_PRIVATE_AZ1_ID=\"\(.inspection_vpc.route_table_private_az1_id // "")\"",
"TF_INSPECTION_RT_PRIVATE_AZ2_ID=\"\(.inspection_vpc.route_table_private_az2_id // "")\"",
"TF_INSPECTION_RT_GWLBE_AZ1_ID=\"\(.inspection_vpc.route_table_gwlbe_az1_id // "")\"",
"TF_INSPECTION_RT_GWLBE_AZ2_ID=\"\(.inspection_vpc.route_table_gwlbe_az2_id // "")\"",
"TF_INSPECTION_RT_TGW_ID=\"\(.inspection_vpc.route_table_tgw_id // "")\"",
"TF_INSPECTION_TGW_ATTACHMENT_ID=\"\(.inspection_vpc.tgw_attachment_id // "")\"",
"TF_INSPECTION_TGW_ROUTE_TABLE_ID=\"\(.inspection_vpc.tgw_route_table_id // "")\"",

# Transit Gateway
"TF_TGW_ID=\"\(.transit_gateway.tgw_id // "")\"",
"TF_TGW_EAST_RT_ID=\"\(.transit_gateway.east_route_table_id // "")\"",
"TF_TGW_WEST_RT_ID=\"\(.transit_gateway.west_route_table_id // "")\"",
"TF_TGW_INSPECTION_RT_ID=\"\(.transit_gateway.inspection_route_table_id // "")\"",
"TF_TGW_EAST_ATTACHMENT_ID=\"\(.transit_gateway.east_attachment_id // "")\"",
"TF_TGW_WEST_ATTACHMENT_ID=\"\(.transit_gateway.west_attachment_id // "")\"",
"TF_TGW_INSPECTION_ATTACHMENT_ID=\"\(.transit_gateway.inspection_attachment_id // "")\"",
"TF_TGW_MGMT_ATTACHMENT_ID=\"\(.transit_gateway.management_attachment_id // "")\"",

# East VPC
"TF_EAST_VPC_ID=\"\(.east_vpc.vpc_id // "")\"",
"TF_EAST_SUBNET_PUBLIC_AZ1_ID=\"\(.east_vpc.subnet_public_az1_id // "")\"",
"TF_EAST_SUBNET_PUBLIC_AZ2_ID=\"\(.east_vpc.subnet_public_az2_id // "")\"",
"TF_EAST_SUBNET_TGW_AZ1_ID=\"\(.east_vpc.subnet_tgw_az1_id // "")\"",
"TF_EAST_SUBNET_TGW_AZ2_ID=\"\(.east_vpc.subnet_tgw_az2_id // "")\"",
"TF_EAST_RT_ID=\"\(.east_vpc.route_table_id // "")\"",
"TF_EAST_LINUX_AZ1_INSTANCE_ID=\"\(.east_vpc.linux_az1_instance_id // "")\"",
"TF_EAST_LINUX_AZ1_PRIVATE_IP=\"\(.east_vpc.linux_az1_private_ip // "")\"",
"TF_EAST_LINUX_AZ1_PUBLIC_IP=\"\(.east_vpc.linux_az1_public_ip // "")\"",
"TF_EAST_LINUX_AZ2_INSTANCE_ID=\"\(.east_vpc.linux_az2_instance_id // "")\"",
"TF_EAST_LINUX_AZ2_PRIVATE_IP=\"\(.east_vpc.linux_az2_private_ip // "")\"",
"TF_EAST_LINUX_AZ2_PUBLIC_IP=\"\(.east_vpc.linux_az2_public_ip // "")\"",

# West VPC
"TF_WEST_VPC_ID=\"\(.west_vpc.vpc_id // "")\"",
"TF_WEST_SUBNET_PUBLIC_AZ1_ID=\"\(.west_vpc.subnet_public_az1_id // "")\"",
"TF_WEST_SUBNET_PUBLIC_AZ2_ID=\"\(.west_vpc.subnet_public_az2_id // "")\"",
"TF_WEST_SUBNET_TGW_AZ1_ID=\"\(.west_vpc.subnet_tgw_az1_id // "")\"",
"TF_WEST_SUBNET_TGW_AZ2_ID=\"\(.west_vpc.subnet_tgw_az2_id // "")\"",
"TF_WEST_RT_ID=\"\(.west_vpc.route_table_id // "")\"",
"TF_WEST_LINUX_AZ1_INSTANCE_ID=\"\(.west_vpc.linux_az1_instance_id // "")\"",
"TF_WEST_LINUX_AZ1_PRIVATE_IP=\"\(.west_vpc.linux_az1_private_ip // "")\"",
"TF_WEST_LINUX_AZ1_PUBLIC_IP=\"\(.west_vpc.linux_az1_public_ip // "")\"",
"TF_WEST_LINUX_AZ2_INSTANCE_ID=\"\(.west_vpc.linux_az2_instance_id // "")\"",
"TF_WEST_LINUX_AZ2_PRIVATE_IP=\"\(.west_vpc.linux_az2_private_ip // "")\"",
"TF_WEST_LINUX_AZ2_PUBLIC_IP=\"\(.west_vpc.linux_az2_public_ip // "")\"",

# Distributed VPCs
"TF_DISTRIBUTED_VPC_COUNT=\"\(.distributed_vpcs.count // 0)\""
' >> "$OUTPUT_FILE"

# Handle distributed VPCs array separately (dynamic number of VPCs)
DISTRIBUTED_COUNT=$(echo "$TF_OUTPUT" | jq -r '.distributed_vpcs.count // 0')
if [ "$DISTRIBUTED_COUNT" -gt 0 ] 2>/dev/null; then
    echo "" >> "$OUTPUT_FILE"
    echo "# Distributed VPC Resources" >> "$OUTPUT_FILE"

    for i in $(seq 0 $((DISTRIBUTED_COUNT - 1))); do
        VPC_NUM=$((i + 1))
        echo "$TF_OUTPUT" | jq -r --argjson idx "$i" --argjson num "$VPC_NUM" '
"TF_DISTRIBUTED_\($num)_VPC_ID=\"\(.distributed_vpcs.vpcs[$idx].vpc_id // "")\"",
"TF_DISTRIBUTED_\($num)_VPC_CIDR=\"\(.distributed_vpcs.vpcs[$idx].vpc_cidr // "")\"",
"TF_DISTRIBUTED_\($num)_IGW_ID=\"\(.distributed_vpcs.vpcs[$idx].igw_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_PUBLIC_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_public_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_PUBLIC_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_public_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_PRIVATE_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_private_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_PRIVATE_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_private_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_GWLBE_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_gwlbe_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_SUBNET_GWLBE_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].subnet_gwlbe_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_PUBLIC_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_public_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_PUBLIC_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_public_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_PRIVATE_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_private_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_PRIVATE_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_private_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_GWLBE_AZ1_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_gwlbe_az1_id // "")\"",
"TF_DISTRIBUTED_\($num)_RT_GWLBE_AZ2_ID=\"\(.distributed_vpcs.vpcs[$idx].route_table_gwlbe_az2_id // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ1_INSTANCE_ID=\"\(.distributed_vpcs.vpcs[$idx].linux_az1_instance_id // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ1_PRIVATE_IP=\"\(.distributed_vpcs.vpcs[$idx].linux_az1_private_ip // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ1_PUBLIC_IP=\"\(.distributed_vpcs.vpcs[$idx].linux_az1_public_ip // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ2_INSTANCE_ID=\"\(.distributed_vpcs.vpcs[$idx].linux_az2_instance_id // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ2_PRIVATE_IP=\"\(.distributed_vpcs.vpcs[$idx].linux_az2_private_ip // "")\"",
"TF_DISTRIBUTED_\($num)_LINUX_AZ2_PUBLIC_IP=\"\(.distributed_vpcs.vpcs[$idx].linux_az2_public_ip // "")\"",
"TF_DISTRIBUTED_\($num)_SECURITY_GROUP_ID=\"\(.distributed_vpcs.vpcs[$idx].security_group_id // "")\""
' >> "$OUTPUT_FILE"
    done
fi

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to parse JSON output"
    rm -f "$OUTPUT_FILE"
    exit 1
fi

echo ""
echo "✓ Verification data generated successfully!"
echo "  File: $OUTPUT_FILE"
echo ""
echo "Verification scripts will now use Terraform outputs instead of AWS CLI lookups."
echo "This makes them faster and more reliable."
echo ""
echo "To regenerate this file after infrastructure changes, run:"
echo "  cd $SCRIPT_DIR"
echo "  ./generate_verification_data.sh"
echo ""

exit 0
